Clarify homeserver configuration and requirements in documentation
matrix-org/matrix-hookshot pull request #243
Opened 2022-03-25 16:56 UTC by Half-Shot

Fixes #238

2022-03-25 17:06 UTC, HarHarLinks requested changes

2022-03-25 17:06 UTC, HarHarLinks commented on docs/setup.md
> +  mediaUrl: http://example.com # Optional. The url where media hosted on your homeserver is reachable (this should be publically reachable from the internet)
```suggestion
  mediaUrl: https://example.com # Optional. The url where media hosted on your homeserver is reachable (this should be publically reachable from the internet)
```

2022-03-25 18:08 UTC, Half-Shot commented on docs/setup.md
> +  domain: example.com # your homeserver's server name
Yep, it's actually official terminology as per https://spec.matrix.org/v1.2/appendices/#server-name

2022-03-26 12:26 UTC, HarHarLinks commented on docs/setup.md
> +  domain: example.com # your homeserver's server name
```suggestion
  domain: example.com # your homeserver's server name per https://spec.matrix.org/v1.2/appendices/#server-name
```

2022-03-28 08:00 UTC, frlan commented on docs/setup.md
> +  domain: example.com # your homeserver's server name
Just to be clear -- "your" is a very wide area. I'd rather see something like "The homeserver hookshot shall communicate with (or similar)

2022-03-28 08:00 UTC, frlan commented
Yes, better.

2022-03-28 10:30 UTC, Half-Shot commented on docs/setup.md
> +  domain: example.com # your homeserver's server name
I would rather the latter, I worry linking the spec at each technical term is going to excessively bog down and confuse users even more. This documentation is also definitely targetted towards people who have:

A) Setup a homeserver themselves
B) Have a "good" understanding of Matrix (not a developer, but enough to understand the concept of multiple servers and the wider federation).

I'll accept we could clarify the "your" here to something more specific.

2022-03-28 10:33 UTC, Half-Shot commented on docs/setup.md
> +  domain: example.com # your homeserver's server name
Have updated the sentence above the snippet to clarify which homeserver we are talking about. I think making anymore changes here feels like hypotethical cases of confusion and I would like to see how this turns out in practice :)

2022-03-28 10:33 UTC, merged