Allow overriding the results of an openID lookup for widgets for local development.
matrix-org/matrix-hookshot pull request #326
Opened 2022-04-29 10:47 UTC by Half-Shot

This is a config option I'd only expect to be used in dev environments, but it basically allows you to map a server hostname to a federation S-S API path for local dev so you don't need a working federated environment to test changes. It's a bit niche, but I've found it useful.

2022-04-29 11:02 UTC, tadzik requested changes

2022-04-29 11:02 UTC, tadzik commented on config.sample.yml
> +    my-local-server: {}
The empty object here doesn't match what Config/Defaults seems to set. What's the format here, and what should one put here for it to work? Does `my-local-server` specifically have any meaning?

2022-05-06 08:42 UTC, tadzik commented on config.sample.yml
> +    my-local-server: {}
I still don't know what the structure is supposed to be :/ Locally I did a 

```
openIdOverrides:
    home.tadzik.net: "http://home.tadzik.net:8080"
```

And that seems to work, but that's not what the documented structure is – it is a `string` => `object` mapping in the docs, while `string` => `string` is what the code expects (and what seems to work).

2022-05-09 10:42 UTC, tadzik requested changes
Still need clarifications

2022-05-09 10:58 UTC, tadzik approved these changes
Now it all fits :)

2022-05-09 11:16 UTC, merged

2024-07-11 04:13 UTC, apoorv569 commented
@Half-Shot What about production servers that have disabled federation completely? Do we put `DOMAIN: https://DOMAIN`? that still wouldn't work I suppose. So what should we put here?