Statically define connection creation and provisioing
matrix-org/matrix-hookshot pull request #330
Opened 2022-05-04 10:27 UTC by Half-Shot

This aims to nearly remove all burden on developers to modify anything outside their connection class when adding new connections. When creating a connection, developers now define their provisioning and creation functions as static functions on their connection class.

Connections can be added by simply adding a `@Connection` decorator.

```ts
@Connection
export class YourConnection {
....
}
```

2022-05-04 10:28 UTC, Half-Shot commented on src/Connections/JiraProject.ts
> +import { Connection, IConnection, IConnectionState, InstantiateConnectionOpts, ProvisionConnectionOpts } from "./IConnection";
For simplicity while we evaluate this idea, I've not committed the changes I've made to other repos.

2022-05-06 13:12 UTC, tadzik approved these changes
Huge +1 from me :) Few nitpicks.

2022-05-06 13:13 UTC, tadzik requested changes
­

2022-05-06 13:14 UTC, Half-Shot commented on src/Bridge.ts
> +                    if (!this.config.jira.url) {
Hm, yeah probably. A empty URL is valid, but the config object should probably set a default value in this case.

2022-05-06 13:25 UTC, Half-Shot commented on src/Bridge.ts
> +            if (!handled && this.connectionManager && this.config.checkPermissionAny(event.sender, BridgePermissionLevel.manageConnections)) {
Not sure, removed.

2022-05-06 13:25 UTC, Half-Shot commented on src/Bridge.ts
> +                    if (!this.config.jira.url) {
Have hopefully solved this now.

2022-05-06 13:27 UTC, tadzik approved these changes

2022-05-06 13:58 UTC, merged