Allow GitLab connections without hook permissions
matrix-org/matrix-hookshot pull request #567
Opened 2022-11-04 15:59 UTC by AndrewFerr

Warn instead of fail when connecting a GitLab project that Hookshot cannot provision a webhook for.

---

This also updates documentation to explain that "Maintainer" or higher permissions are required on a GitLab project for Hookshot to be able to add a webhook to it.

The warning appears for both `hookshot gitlab project <url>` and the widget:
![Screenshot from 2022-11-04 11-38-31](https://user-images.githubusercontent.com/3271094/200020619-a343b636-8b70-430f-9c6d-c7271ab827c8.png)

2022-11-04 16:05 UTC, AndrewFerr commented
Fixes #545

2022-11-07 11:48 UTC, Half-Shot commented on web/components/roomConfig/RoomConfig.tsx
> +            error && <ErrorPane header={error.header || "Error"} isWarning={error.isWarning}>{error.message}</ErrorPane>
I'd either do <ErrorPane kind="warning"> *or* <WarningPane> (preference on the latter). `isWarning` feels clunky.

2022-11-07 11:51 UTC, Half-Shot requested changes

2022-11-07 11:51 UTC, Half-Shot commented on web/components/elements/ErrorPane.tsx
> +    return <div class={`card error ${isWarning ? style.warningPane : style.errorPane}`}>
Yeah, the `isWarnings here make me feel this should be a separate function :D

2022-11-07 11:51 UTC, Half-Shot commented on web/components/elements/ErrorPane.module.scss
> +    color: #CCAA00;
This colour isn't great for contrast, have you consulted the Figma Oracles?

https://www.figma.com/file/KhVjYAzy4oX3eIqwu9KQxN/Element-library?node-id=4779%3A18811
https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=557%3A0

2022-11-08 09:45 UTC, Half-Shot approved these changes
Smashing!

2022-11-08 15:19 UTC, merged