Implement separate bot users per service
matrix-org/matrix-hookshot pull request #573
Opened 2022-11-17 21:27 UTC by justinbot

Introduces the ability for Hookshot to present itself as multiple different bots, each of which can handle one or more specific services. This is a pretty fundamental change, and as a result touches almost everywhere.

It should be relatively reviewable by commit, but will require significant testing of different scenarios to make sure things work correctly.

### Implementation
Fundamentally, this is breaking an assumption throughout the codebase that there is one global bot. The implications are:
  * Before interacting with a room, we need to find a bot which is in the room.
      * But also, multiple bots could be in the same room.
  * When doing so in the context of a particular service (e.g. sending a feed update), we need to prioritize the service bot over the default bot.

#### Connections
However, this does not mean connections are tied to a specific bot user.
We need to choose the right bot for a connection, but this is done at runtime based on which bots are in the room (again prioritizing service bots).

## TODO
- [ ] Implement admin rooms for service bots
- [x] Use service bots for feeds
- [ ] Use service bots for webhooks
- [ ] Use service bots for github
- [ ] Use service bots for gitlab
- [ ] Use service bots for figma
- [ ] Use service bots for jira

Fixes #436

2022-12-21 12:45 UTC, Half-Shot requested changes
Bunch of comments, @tadzik has more :)

2022-12-21 12:45 UTC, Half-Shot commented on src/Managers/JoinedRoomsManager.ts
> +    // Map of room ID to set of our bot user IDs in the room
I think this class logic could b be merged into `BotUsersManager`? It seems quite intertwined.

2022-12-21 12:45 UTC, Half-Shot commented on src/Bridge.ts
> +        const botUser = this.botUsersManager.getBotUser(invitedUserId);
Could getBotUser return an object that returns an intent, to save on LoC.

2022-12-21 12:45 UTC, Half-Shot commented on src/Bridge.ts
> +        const botUser = this.botUsersManager.getBotUser(invitedUserId);
Could we also be explicit and call this a serviceBotUser so it doesn't confuse with the sender_localpart user.

2022-12-21 12:45 UTC, Half-Shot commented on src/Bridge.ts
> +            await this.connectionManager.createConnectionsForRoomId(roomId, true);
This should probably be a dedicated handover function. Our connections are slightly stateful and it's better to not recreate them v.s. updating them, if we can avoid it.

2022-12-21 12:45 UTC, Half-Shot commented on src/Bridge.ts
> +                        const setupConnection = new SetupConnection(
Could setup connection instead take the `botUsersInRoom` and iterate within the connection, rather than recreating the connection in a loop?

2023-01-05 09:39 UTC, jaller94 commented on src/Connections/GenericHook.ts
> +        const [, domain] = this.intent.userId.split(':');
PR #600

2023-01-11 15:59 UTC, Half-Shot commented on src/Connections/FigmaFileConnection.ts
> +        if (this.config.overrideUserId) {
Can we gracefully assume that if overrideUserId is set in the config, we should warn about deprecation and create a service bot for it?

If the service bot config is *also*  defined, then skip it and fail if it's still defined in the config.

2023-01-13 15:27 UTC, Half-Shot commented on src/Bridge.ts
> +                        const setupConnection = new SetupConnection(
I think we decided this was fine in the end.

2023-01-13 15:27 UTC, Half-Shot approved these changes

2023-01-13 15:30 UTC, Half-Shot commented on src/Bridge.ts
>          await this.config.prefillMembershipCache(this.as.botClient);
I think this is fine, we can use the lead bot for this one.

2023-01-13 15:32 UTC, merged