Create alertmanager.js
matrix-org/matrix-hookshot pull request #808
Opened 2023-08-08 16:17 UTC by HarHarLinks

2023-08-08 17:02 UTC, Half-Shot requested changes
Thanks for this one :). Just a couple of requests from me.

2023-08-08 17:02 UTC, Half-Shot commented on contrib/alertmanager.js
> +function statusBadge(status, severity) {
I'd:

- Put this in a subdirectory like jsTransformationFunctions
- Add a simple description of what this does in docstring.

2023-08-09 15:39 UTC, HarHarLinks commented
@erebion thanks for the screenshots.
I agree with your sentiment. However I'm not actively using this (just copy-pasted from the hookshot channel), I'm not even running Alertmanager, yet...
I think it'd be best if you could suggest changes via code review?

2023-08-14 13:50 UTC, Half-Shot commented on contrib/jsTransformationFunctions/alertmanager.js
> +            return `<font color='orange'><b>[FIRING - WARNING]</b></font>`;
I'm not a massive fan of `<br>`. Can we paragraph the event content instead with `<p>` and have the client give it appropriate spacing?

2023-08-14 14:56 UTC, HarHarLinks commented
```
"formatted_body": "<p><font color='green'><b>[RESOLVED]</b></font></p><p><b>HostSystemdServiceCrashed</b>: SystemD service crashed<br/>  VALUE = 1<br/>  LABELS: map[__name__:node_systemd_unit_state instance:localhost:9100 job:host_node_exporter name:grafana.service state:failed type:simple]</p><p><a href=\"http://erebion-matrix:9090/graph?g0.expr=node_systemd_unit_state%7Bstate%3D%22failed%22%7D+%3D%3D+1&g0.tab=1\">source</a> | <a href=\"http://localhost:9093#silences/new?filter={alertname%3D%22HostSystemdServiceCrashed%22,instance%3D%22localhost%3A9100%22,job%3D%22host_node_exporter%22,name%3D%22grafana.service%22,severity%3D%22warning%22,state%3D%22failed%22,type%3D%22simple%22}\">silence</a></p>"
```
looks like
![image](https://github.com/matrix-org/matrix-hookshot/assets/2803622/807729ae-1895-49a5-a5f1-6847ddd61fd7)

2023-08-16 17:12 UTC, merged