Add ability to respond to webhooks.
matrix-org/matrix-hookshot pull request #838
Opened 2023-11-08 15:03 UTC by Half-Shot

Fixes #837 

This adds two new features to the generic webhook connection type:
 - The ability to set a response value for webhooks.
 - The ability for connections to choose whether to block on the webhook function before responding.

2023-11-08 17:55 UTC, Twi1ightSparkle commented
Hookshot is posting the message twice to Matrix both with and without `Wait for webhook function to complete before responding` checked. But looks to be sending the correct data back.

```javascript
const responseBody = `
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Body>
<notificationsResponse xmlns="http://soap.sforce.com/2005/09/outbound">
<Ack>true</Ack>
</notificationsResponse>
</soapenv:Body>
</soapenv:Envelope>
`.trim();

result = {
    empty: false,
    msgtype: 'm.text',
    plain: message,
    version: 'v2',
    webhookResponse: {
        body: responseBody,
        contentType: 'application/xml',
        statusCode: 418,
    }
};
```

![Screenshot 2023-11-08 at 5 41 52 PM](https://github.com/matrix-org/matrix-hookshot/assets/19155609/003a3a01-2af5-4d52-9b27-dd4d4831eb7d)

---

Also, `Wait for webhook function to complete before responding` unchecks itself when you close and re-open the webhook in the configurator.

---

Waiting for my contact to do an actual test with Salesforce.

2023-11-08 18:01 UTC, Twi1ightSparkle commented
Actually, once you have enabled `Wait for webhook function to complete before responding.`, you can't turn it off again. It appears to just not read `waitForComplete": true` from the `"uk.half-shot.matrix-hookshot.generic.hook",` state event when opening the webhook

2023-11-15 07:00 UTC, AndrewFerr requested changes

2023-11-15 09:21 UTC, Half-Shot commented on CHANGELOG.md
> +4.5.1 (2023-11-09)
Well spotted, how did that happen :/

2023-11-15 09:22 UTC, Half-Shot commented on docs/setup/webhooks.md
> +for this is that some services expect a quick response time (Slack) whereas others will wait for the request to complete. You
I meant Slack, but I should probably make that clearer.

2023-11-20 12:39 UTC, AndrewFerr approved these changes

2023-11-20 12:45 UTC, merged