Change example Openid Connect callback url's to be correct.
matrix-org/matrix-hookshot pull request #899
Opened 2024-02-21 15:00 UTC by minecraftchest1

The docs suggested that the Openid Connect callback url's should be at `/bridge_oauth`, but it should actually point to `/oauth

Resolves https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$surQW-4XHEJ8wgzzOClOF0QoWM-jjA1V5X3BlNQfQaw?via=half-shot.uk&via=matrix.org&via=element.io`

2024-02-21 16:14 UTC, Half-Shot commented on config.sample.yml
> +#    redirect_uri: https://example.com/oauth/
You'll need to update it in https://github.com/matrix-org/matrix-hookshot/blob/main/src/config/Defaults.ts#L69 too, as this file is generated from that.

2024-02-23 09:42 UTC, Half-Shot requested changes
tweak the config .ts files, and add a newsfile and you're done!

2024-02-23 14:49 UTC, minecraftchest1 commented
Should I create two changelog files (one for the defaults in the source code, and one for the docs)?

2024-02-26 08:45 UTC, Half-Shot approved these changes
Nice!

2024-02-26 08:52 UTC, merged